// FUNCIONES PARA PEGAR CON javascript_tool (Claude in Chrome). Se pierden al recargar la pestaña: volver a pegarlas.
// OJO: la extensión bloquea salidas (y a veces código) con "=", "?" o "&": limpiar la salida con .replace(/[=?&]/g,' ')
// y armar URLs con String.fromCharCode(63) (?) 61 (=) 38 (&).

// ===== 1) PESTAÑA DE ML DE BÚSQUEDA: abrir https://listado.mercadolibre.com.ar/<algo> y pegar esto =====
window.norm=s=>s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]/g,'');
window.estM=(P,usd)=> (P*0.86-(P>=33000?7500:0))/(usd*1.17*1535)-1;   // SÓLO filtro grueso de margen
window.__mlres=window.__mlres||{};
window.mlSearch = async (q)=>{ const raw=await (await fetch('/'+q.trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]+/g,'-'))).text(); const h=raw.replace(/\\u002F/g,'/').replace(/\\"/g,'"'); const pos=[]; let re=/"polycard":\{/g, m; while((m=re.exec(h))) pos.push(m.index); pos.push(h.length); const res=[]; for(let i=0;i<pos.length-1;i++){ const c=h.slice(pos[i], Math.min(pos[i+1], pos[i]+12000)); const g=r=>(c.match(r)||[])[1]; res.push({id:g(/"id":"(MLA\d+)"/), pid:g(/"product_id":"(MLA\d+)"/), t:(g(/"title":\{"text":"([^"]+)"/)||''), p:+(g(/"price":(\d+)/)||0), sold:+(g(/"sold_quantity":(\d+)/)||0), full:/full_icon/.test(c), intl:/cbt_|cross_border|_cbt/i.test(c)}); } return res; };
window.modelKeys=(q)=>{ const w=q.split(/\s+/).filter(Boolean); const keys=[]; w.forEach((x,i)=>{ if(/\d/.test(x)){ const nx=norm(x); if(/^\d{1,2}$/.test(nx) && i>0) keys.push(norm(w[i-1])+nx); else if(nx.length>=2) keys.push(nx); } }); return {brand:norm(w[0]||''), keys}; };
window.matchQ=(q,t)=>{ const {brand,keys}=modelKeys(q); const nt=norm(t); if(brand && !nt.includes(brand)) return false; if(keys.length) return keys.every(k=>nt.includes(k)); const w=q.split(/\s+/).slice(1).map(norm).filter(x=>x.length>=3); return w.length? w.every(k=>nt.includes(k)) : true; };
window.mlScan = async (qs, minM, minSold)=>{ minM=minM??0.15; minSold=minSold??50; const out=[]; let done=0; for(const [q,usd,n,i] of qs){ try{ let r=(await mlSearch(q)).filter(x=>x.pid && !x.intl); const match=r.filter(x=>matchQ(q,x.t)); window.__mlres[q]={usd, all:r.slice(0,12), match}; done++; if(!match.length) continue; const best=match.slice().sort((a,b)=>b.sold-a.sold)[0]; const cheapest=match.filter(x=>x.sold>=minSold).sort((a,b)=>a.p-b.p)[0]||best; const e=estM(cheapest.p,usd); if(e>=minM && best.sold>=minSold) out.push(i+' '+q.slice(0,30)+' $'+usd+' -> '+cheapest.pid+' $'+cheapest.p+' v'+best.sold+' '+Math.round(e*100)+'% '+cheapest.t.slice(0,28)); }catch(e){ out.push(i+' ERR '+q); } } return done+'/'+qs.length+' ok\n'+out.join('\n'); };
// tandas largas en segundo plano (la herramienta corta a los ~45 s): scanBg(lista) y después mirar window.__scan
window.scanBg=(qs,minM,minSold)=>{ window.__scan={running:true, out:'', started:Date.now(), n:qs.length}; mlScan(qs,minM,minSold).then(o=>{window.__scan.out=o; window.__scan.running=false;}).catch(e=>{window.__scan.out='ERR '+e; window.__scan.running=false;}); return 'lanzado '+qs.length; };
// lista de catálogos de un modelo (para elegir el COLOR): mlFind([['jbl tune 520c',/520c/i], ...])
window.mlFind = async (qs)=>{ const out=[]; for(const [q,re] of qs){ const r=(await mlSearch(q)).filter(x=>x.pid && re.test(x.t)); const seen=new Set(); const u=r.filter(x=>!seen.has(x.pid)&&seen.add(x.pid)).sort((a,b)=>b.sold-a.sold).slice(0,4); out.push('## '+q+'\n'+u.map(x=>'  '+x.pid+' $'+x.p+' v'+x.sold+(x.full?'F':'')+' '+x.t.slice(0,58)).join('\n')); } return out.join('\n').replace(/[=?&]/g,' '); };

// ===== 2) PESTAÑA DE ML DE CATÁLOGO: abrir https://www.mercadolibre.com.ar/p/MLA6072235 (cualquiera) y pegar esto =====
// mlCat: título, precio de la ganadora, "+N vendidos" de la ganadora, Full y la foto
window.mlCat = async (pid)=>{ const html=await (await fetch('/p/'+pid)).text(); const d=new DOMParser().parseFromString(html,'text/html'); const t=(d.body.textContent||'').replace(/\s+/g,' '); const h1=(d.querySelector('h1')||{}).textContent||''; const pr=(d.querySelector('.ui-pdp-price__second-line .andes-money-amount__fraction')||{}).textContent||''; const sold=(t.match(/\+?[\d.]+ vendidos/)||[])[0]||''; const full=/full_icon|ui-pdp-icon--full|"full"/i.test(html); const img=(html.match(/https:\/\/http2\.mlstatic\.com\/D_NQ_NP_[^"' ]+?-O\.(webp|jpg)/)||[])[0]||''; return {pid, h1:h1.trim(), pr, sold, full, img}; };
// mlCuotas: cuántas cuotas ofrece la publicación que GANA. 2 (o ninguna) = no cuenta (lo da ML a todos). 6 o 9 = costo real.
window.mlCuotas = async (pid)=>{ const html=await (await fetch('/p/'+pid)).text(); const d=new DOMParser().parseFromString(html,'text/html'); const t=(d.body.textContent||'').replace(/\s+/g,' '); const m=t.match(/Mismo precio en (\d+) cuotas/); return m?+m[1]:0; };

// ===== 3) PESTAÑA DEL PANEL (https://maticaldas-del.github.io/web-cyc/) =====
// Cargar candidatos nuevos en "Para probar" (ruta candidatos_py). Cada fila: [cod, usd, nombre, href de comprasparaguay, archivo de la foto, mlId(catálogo), vendidos, marca]
window.cargarCand = async (rows)=>{ const B='https://bucket-prod.us-ord-10.linodeobjects.com/site/media/fotos/produtos/thumbs/med/'; const C='https://comprasparaguay.com.ar'; const out=[]; for(const [cod,usd,nombre,h,img,mlId,vend,marca] of rows){ const ya=Object.values(state.candidatos).find(x=>String(x.cod)===cod); if(ya){ out.push(cod+' YA EXISTE'); continue; } const id='c'+Date.now(); await fbSet('candidatos_py/'+id, {nombre, cod, usd, link:C+h, mlId, vendCarga:vend, foto:B+img, marca, fuente:'chat', enNissei:true, ts:Date.now()}); const v=(await db.ref('cyc/candidatos_py/'+id).once('value')).val()||{}; out.push(cod+' -> '+id+(v.mlId===mlId?' ok':' FALLO')); await new Promise(r=>setTimeout(r,15)); } return out.join('\n'); };
// Probados (fichas origen 'py' en state.products): updNisseiUSD(id,precio) · updNisseiCod(id,'codigo') · pyNoHabia(id,true). NUNCA tocar costUSD.
// Cargar de a 5-6 por llamada: con 10 la pestaña se trabó (igual se guardaron; releer con db.ref('cyc/candidatos_py').once('value')).
